name: CI/CD AKS GitOps

on:
  push:
    branches: [ main ]

env:
  # ATENÇÃO: Verifique se o seu Secret no GitHub NÃO tem o .azurecr.io
  # Se tiver, mude aqui para: ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_NAME: azureappkazu.azurecr.io 
  APP_NAME: azure-app-kazu

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name azureappkazu

      - name: Build and Push
        run: |
          # Build usando o SHA do commit como tag
          docker build -t ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Importante para o push funcionar
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Update Kustomize Tag
        run: |
          cd argocd/apps/node-app/overlays/staging
          # Este comando troca o 'PLACEHOLDER' pelo SHA do commit atual
          kustomize edit set image node-app=${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "deploy: update staging image to ${{ github.sha }} [skip ci]"
          git push