name: CI/CD AKS

on:
  push:
    branches: [main]

env:
  ACR_NAME: azureappkazu.azurecr.io    # <-- NOME NOVO
  APP_NAME: azure-app-kazu             
  RESOURCE_GROUP: azure-devops         
  AKS_NAME: aks-kazu
jobs:
  # ========== CI: BUILD + PUSH ==========
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 1. Autenticar o Docker no seu ACR
      - name: Login to ACR
        run: |
          az acr login --name azureappkazu

      # 2. Buildar a imagem usando o processador do GitHub
      - name: Build and Tag Image
        run: |
          docker build -t ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} .
          docker build -t ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:latest .

  # ========== CD: UPDATE GIT (GitOps) ==========
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB }}

      - name: Update K8s manifest
        run: |
          # Garanta que esta linha abaixo seja uma única linha no seu arquivo
          sed -i "s|image:.*|image: ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}|" k8s/deployment.yaml
      
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "deploy: update image to ${{ github.sha }}" || echo "No changes"
          git push